#!/bin/bash
rm *.info *.out
make clean
make ecm
echo -e "**** ECM ****" > coverage.out
./ecm "221313+sumdigits(23,10)+numdigits(232,10)+revdigits(765,10)+gcd(8,6)+minfact(143)+totient(226)+jacobi(3,7)+modpow(3,8,29)" >> coverage.out
./ecm "n(10^30+2)*n(3*10^30+10000)" >> coverage.out
./ecm "10**59+213" >> coverage.out
./ecm "p(655) % 65657578" >> coverage.out
./ecm "modinv(6,13)-numdivs(45)+sumdivs(343)+maxfact(765)+numfact(765)+concatfact(0,36)+concatfact(0,36)+concatfact(1,36)+concatfact(2,36)+concatfact(3,36)+isprime(811)" >> coverage.out
./ecm "b(223)+n(434)+f(44)-l(56)+23!-18#" >>coverage.out
./ecm "(23 shl 5) + (712 shr 6) + (23 OR 556) + (57 AND 21) + (NOT 15) + (38 XOR 79) + 4434/115 - 28%13" >>coverage.out
./ecm "(6 > 5)*32 + (6 >= 5)*16 + (6 < 5)*8 + (6 <= 5)*4 + (6 == 5)*2 + (6 != 5)" >>coverage.out
./ecm "(7 > 7)*32 + (7 >= 7)*16 + (7 < 7)*8 + (7 <= 7)*4 + (7 == 7)*2 + (7 != 7)" >>coverage.out
./ecm "x=3; x=n(x); c<=10; x-1" >> coverage.out
./ecm "sqrt(10^10000)-10^5000" >> coverage.out
lcov --capture --directory . --output-file ecm.info
make clean
make polfact
echo -e "\n\n**** POLFACT ****" >> coverage.out
./polfact 0 "x^120-1" >> coverage.out
./polfact 7 "x^10+x^5-1" >> coverage.out
./polfact 0 "x+23" >> coverage.out
./polfact 0 "x^2+7*x+23" >> coverage.out
./polfact 0 "x^3-4*x^2+12*x+23" >> coverage.out
./polfact 0 "x^4+3*x^2+12*x+23" >> coverage.out
./polfact 0 "x^5+15*x+12" >> coverage.out
./polfact 0 "(x^2-3*x+5)^2*(x+1)^5*(x-23)*x^9" >> coverage.out
./polfact 0 "der(x^8)+gcd(x^7+x^5+2, x^3+43*x)" >> coverage.out
./polfact 7 "der(x^8)+gcd(x^7+x^5+2, x^3+43*x)" >> coverage.out
lcov --capture --directory . --output-file polfact.info
make clean
make fsquares
echo -e "\n\n**** FSQUARES ****" >> coverage.out
./fsquares 0 >> coverage.out
./fsquares 27 >> coverage.out
./fsquares "10**200+54154255642" >> coverage.out
lcov --capture --directory . --output-file fsquares.info
make clean
make fcubes
echo -e "\n\n**** FCUBES ****" >> coverage.out
./fcubes 0 >> coverage.out
./fcubes 27 >> coverage.out
./fsquares "10**200+54154255642" >> coverage.out
lcov --capture --directory . --output-file fcubes.info
make clean
make dilog
echo -e "\n\n**** DILOG ****" >> coverage.out
./dilog 3 7 29 >> coverage.out
./dilog 28 43 "n(120000)" >> coverage.out
./dilog 667 999 "n(10000000000)" >> coverage.out
lcov --capture --directory . --output-file dilog.info
make clean
make quad
echo -e "\n\n**** QUAD ****" >> coverage.out
./quad 1 2 3 4 5 6 >> coverage.out
./quad 1 0 "-991" 0 0 "-1" >> coverage.out
./quad 5 3 "-991" 23 42 "-1" >> coverage.out
lcov --capture --directory . --output-file quad.info
make clean
make contfrac
echo -e "\n\n**** CONTFRAC ****" >> coverage.out
./contfrac 1 2 3 >> coverage.out
./contfrac 1 0 991 >> coverage.out
./contfrac 5 27 991 >> coverage.out
lcov --capture --directory . --output-file contfrac.info
make clean
make quadmod
echo -e "\n\n**** QUADMOD ****" >> coverage.out
./quadmod 1 2 3 7 >> coverage.out
./quadmod 1 0 991 "n(10^5)" >> coverage.out
./quadmod 5 27 43 "n(10^20+3)" >> coverage.out
./quadmod 5 27 82 "n(10^80+5)" >> coverage.out
lcov --capture --directory . --output-file quadmod.info
make clean
make gaussian
echo -e "\n\n**** GAUSSIAN ****" >> coverage.out
./gaussian 5 1 >> coverage.out
./gaussian 1 1 >> coverage.out
./gaussian "232435+432i" 1 >> coverage.out
./gaussian "10**20+45+(23i)" 1 >> coverage.out
lcov --capture --directory . --output-file gaussian.info

while true; do
    read -p "Output OK? (Y/N) " yn
    case $yn in
        [Yy]* ) break;;
        [Nn]* ) exit;;
        * ) echo "Please answer yes or no.";;
    esac
done
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r ecm.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r polfact.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r fsquares.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r fcubes.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r dilog.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r quad.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r quadmod.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r contfrac.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) report --partial -r gaussian.info
bash <(curl -Ls https://coverage.codacy.com/get.sh) final
